#!/usr/bin/env php
<?php

// require autoload file
$autoloads = [__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php'];
foreach ($autoloads as $file) {
  if (file_exists($file)) {
    define('REIWADATETIME_COMPOSER_INSTALL', $file);
    break;
  }
}
require REIWADATETIME_COMPOSER_INSTALL;

$datetime = isset($argv[1]) ? $argv[1] : null;

try{
  $d = new RobustInc\ReiwaDateTime\ReiwaDateTime($datetime);
  echo $d->localize("只今 Y年m月d日 です。") . PHP_EOL;
}catch(\Exception $e){
  echo "正しい日付を入力してください" . PHP_EOL;
  exit(1);
}
